apiVersion: v1
kind: Pod
metadata:
  name: image-pull-test
spec:
  containers:
  - name: image-pull-container
    image: northamerica-northeast2-docker.pkg.dev/useful-variety-415821/sofe3980u/binarycalculator
    ports:
    - containerPort: 8080
  restartPolicy: Never